# Generated by Django 3.2.7 on 2021-09-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
    ]
