# Generated by Django 3.2.7 on 2021-09-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
