# Generated by Django 3.2.7 on 2021-09-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioagenda',
            name='disponivel',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
