# Generated by Django 3.2.7 on 2021-09-26 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2021, 9, 26, 19, 58, 52, 895164, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
