# Generated by Django 3.2.7 on 2021-09-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_data_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['dia', 'horario']},
        ),
    ]
